# fly.toml app configuration file generated for api-hacker-news-clone on 2025-09-14T20:49:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-hacker-news-clone'
primary_region = 'atl'

[build]
  dockerfile = "Dockerfile"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  method = "GET"
  path = "/api/health"
  interval = "10s"
  timeout = "2s"
  grace_period = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
